/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mako.view;

import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import mako.controller.ProdutoDAO;
import mako.controller.Relatorio;
import mako.controller.Watermark;
import mako.model.Produto;

/**
 *
 * @author CaioThizio
 */
public class CadastroProduto extends javax.swing.JFrame {
    private Produto p = new Produto();
    public static ArrayList<String> tipos;
    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelProduto = new javax.swing.JPanel();
        apresentacaoProduto = new javax.swing.JLabel();
        painelCamposProduto = new javax.swing.JPanel();
        labelNomeProduto = new javax.swing.JLabel();
        textNomeProduto = new javax.swing.JTextField();
        labelNomeFornProduto = new javax.swing.JLabel();
        textFornProduto = new javax.swing.JTextField();
        labelQtdProduto = new javax.swing.JLabel();
        labelIDProduto = new javax.swing.JLabel();
        textIDProduto = new javax.swing.JTextField();
        labelTipoProduto = new javax.swing.JLabel();
        labelCustoProduto = new javax.swing.JLabel();
        textCustoProduto = new javax.swing.JTextField();
        labelRevendaProduto = new javax.swing.JLabel();
        textRevendaProduto = new javax.swing.JTextField();
        labelObsProduto = new javax.swing.JLabel();
        buttonVoltarProduto = new javax.swing.JButton();
        buttonLimparProduto = new javax.swing.JButton();
        buttonCadastrarProduto = new javax.swing.JButton();
        buttonBanco = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaObsProduto = new javax.swing.JTextArea();
        textQtde = new javax.swing.JTextField();
        buttonrRelatorioC = new javax.swing.JButton();
        comboBoxTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Produto");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        painelProduto.setBackground(new java.awt.Color(0, 204, 204));
        painelProduto.setForeground(new java.awt.Color(255, 255, 255));
        painelProduto.setPreferredSize(new java.awt.Dimension(720, 600));

        apresentacaoProduto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        apresentacaoProduto.setForeground(new java.awt.Color(255, 255, 255));
        apresentacaoProduto.setText("Cadastro de Produtos");

        painelCamposProduto.setBackground(new java.awt.Color(255, 255, 255));

        labelNomeProduto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelNomeProduto.setText("Nome do Produto:");

        textNomeProduto.setUI(new mako.controller.Watermark("Digite o nome do Produto...", true));

        labelNomeFornProduto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelNomeFornProduto.setText("Nome do Fornecedor:");

        textFornProduto.setUI(new mako.controller.Watermark("Digite o nome do Fornecedor deste Produto...", true));

        labelQtdProduto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelQtdProduto.setText("Quantidade:");

        labelIDProduto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelIDProduto.setText("ID do Produto:");

        textIDProduto.setUI(new mako.controller.Watermark("Digite o ID do Produto...", true));

        labelTipoProduto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelTipoProduto.setText("Tipo do Produto:");

        labelCustoProduto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelCustoProduto.setText("Preço de Custo (R$):");

        textCustoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCustoProdutoActionPerformed(evt);
            }
        });

        labelRevendaProduto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelRevendaProduto.setText("Preço de Revenda (R$):");

        textRevendaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRevendaProdutoActionPerformed(evt);
            }
        });

        labelObsProduto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelObsProduto.setText("Observações:");

        buttonVoltarProduto.setText("Voltar");
        buttonVoltarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonVoltarProdutoMouseClicked(evt);
            }
        });

        buttonLimparProduto.setText("Limpar Campos");
        buttonLimparProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLimparProdutoMouseClicked(evt);
            }
        });

        buttonCadastrarProduto.setText("Cadastrar");
        buttonCadastrarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCadastrarProdutoMouseClicked(evt);
            }
        });

        buttonBanco.setText("Abrir Banco");
        buttonBanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBancoMouseClicked(evt);
            }
        });

        textAreaObsProduto.setColumns(20);
        textAreaObsProduto.setLineWrap(true);
        textAreaObsProduto.setRows(5);
        jScrollPane1.setViewportView(textAreaObsProduto);

        textQtde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQtdeActionPerformed(evt);
            }
        });

        buttonrRelatorioC.setText("Relatório de Produtos");
        buttonrRelatorioC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonrRelatorioCMouseClicked(evt);
            }
        });
        buttonrRelatorioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonrRelatorioCActionPerformed(evt);
            }
        });

        popularComboBox();

        javax.swing.GroupLayout painelCamposProdutoLayout = new javax.swing.GroupLayout(painelCamposProduto);
        painelCamposProduto.setLayout(painelCamposProdutoLayout);
        painelCamposProdutoLayout.setHorizontalGroup(
            painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                        .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCamposProdutoLayout.createSequentialGroup()
                                .addComponent(labelCustoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                                .addComponent(labelRevendaProduto)
                                .addGap(9, 9, 9)))
                        .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(textCustoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textRevendaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                        .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelIDProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNomeFornProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(labelNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                                .addComponent(buttonBanco)
                                .addGap(18, 18, 18)
                                .addComponent(buttonrRelatorioC))
                            .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                                .addComponent(textFornProduto)
                                .addComponent(textIDProduto))))
                    .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                        .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTipoProduto)
                            .addComponent(labelQtdProduto)
                            .addComponent(labelObsProduto))
                        .addGap(56, 56, 56)
                        .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                                .addComponent(buttonVoltarProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonLimparProduto)
                                .addGap(99, 99, 99)
                                .addComponent(buttonCadastrarProduto))
                            .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                                    .addComponent(textQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        painelCamposProdutoLayout.setVerticalGroup(
            painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBanco)
                    .addComponent(buttonrRelatorioC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIDProduto)
                    .addComponent(textIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeProduto)
                    .addComponent(textNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeFornProduto)
                    .addComponent(textFornProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCustoProduto)
                    .addComponent(textCustoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRevendaProduto)
                    .addComponent(textRevendaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQtdProduto)
                    .addComponent(textQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoProduto)
                    .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labelObsProduto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVoltarProduto)
                    .addComponent(buttonLimparProduto)
                    .addComponent(buttonCadastrarProduto))
                .addContainerGap())
        );

        javax.swing.GroupLayout painelProdutoLayout = new javax.swing.GroupLayout(painelProduto);
        painelProduto.setLayout(painelProdutoLayout);
        painelProdutoLayout.setHorizontalGroup(
            painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelProdutoLayout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(apresentacaoProduto)
                .addGap(233, 233, 233))
            .addComponent(painelCamposProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelProdutoLayout.setVerticalGroup(
            painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProdutoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(apresentacaoProduto)
                .addGap(18, 18, 18)
                .addComponent(painelCamposProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(painelProduto);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLimparProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLimparProdutoMouseClicked
        textIDProduto.setText("");
        textNomeProduto.setText("");
        textFornProduto.setText("");
        textCustoProduto.setText("");
        textRevendaProduto.setText("");
        textAreaObsProduto.setText("");
        textQtde.setText("");
        //textTipo.setText("");
    }//GEN-LAST:event_buttonLimparProdutoMouseClicked

    private void buttonCadastrarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCadastrarProdutoMouseClicked
        int op = JOptionPane.showConfirmDialog(null, "Tem certeza que gostaria de cadastrar o produto?", "Cadastro de Produto", JOptionPane.YES_NO_OPTION);

        if (op == 0){
            
            p.setId(Integer.parseInt(textIDProduto.getText()));
            p.setNome(textNomeProduto.getText());
            p.setPrecoCusto(Double.parseDouble(textCustoProduto.getText()));
            p.setPrecoRevenda(Double.parseDouble(textRevendaProduto.getText()));
            p.setQtde(Integer.parseInt(textQtde.getText()));
            p.setListaTipo(comboBoxTipo.getSelectedItem().toString());
            p.setObs(textAreaObsProduto.getText());
            
            
            
            JOptionPane.showMessageDialog(null,ProdutoDAO.cadastrar(p), "Cadastro de Produto", JOptionPane.PLAIN_MESSAGE);
            ProdutoDAO.adicionarProdutoBD(p);
            //ProdutoDAO.escreveProdutos();
            //ProdutoDAO.escreveProdutosBin();
            
        }
    }//GEN-LAST:event_buttonCadastrarProdutoMouseClicked

    private void textRevendaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRevendaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRevendaProdutoActionPerformed

    private void textCustoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCustoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCustoProdutoActionPerformed

    private void buttonVoltarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVoltarProdutoMouseClicked
        this.dispose();
    }//GEN-LAST:event_buttonVoltarProdutoMouseClicked

    private void textQtdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQtdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQtdeActionPerformed

    private void buttonBancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBancoMouseClicked
        new BancoProdutos().setVisible(true);
    }//GEN-LAST:event_buttonBancoMouseClicked

    private void buttonrRelatorioCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonrRelatorioCMouseClicked
        Relatorio.mostraRelatorioProdutos();
    }//GEN-LAST:event_buttonrRelatorioCMouseClicked

    private void buttonrRelatorioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonrRelatorioCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonrRelatorioCActionPerformed

    public void popularComboBox(){
        tipos = new ArrayList<>();
        
        tipos.add("Pincel/Kit");
        tipos.add("Paleta");
        tipos.add("Batom");
        tipos.add("Sombra");
        tipos.add("Blush");
        tipos.add("Iluminador");
        tipos.add("Rímel");
        tipos.add("Lápis de Olho");
        tipos.add("Delineador");
        tipos.add("Outros");
        
        tipos.forEach((tipo) -> {
            comboBoxTipo.addItem(tipo);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apresentacaoProduto;
    private javax.swing.JButton buttonBanco;
    private javax.swing.JButton buttonCadastrarProduto;
    private javax.swing.JButton buttonLimparProduto;
    private javax.swing.JButton buttonVoltarProduto;
    private javax.swing.JButton buttonrRelatorioC;
    private javax.swing.JComboBox<String> comboBoxTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCustoProduto;
    private javax.swing.JLabel labelIDProduto;
    private javax.swing.JLabel labelNomeFornProduto;
    private javax.swing.JLabel labelNomeProduto;
    private javax.swing.JLabel labelObsProduto;
    private javax.swing.JLabel labelQtdProduto;
    private javax.swing.JLabel labelRevendaProduto;
    private javax.swing.JLabel labelTipoProduto;
    private javax.swing.JPanel painelCamposProduto;
    private javax.swing.JPanel painelProduto;
    private javax.swing.JTextArea textAreaObsProduto;
    private javax.swing.JTextField textCustoProduto;
    private javax.swing.JTextField textFornProduto;
    private javax.swing.JTextField textIDProduto;
    private javax.swing.JTextField textNomeProduto;
    private javax.swing.JTextField textQtde;
    private javax.swing.JTextField textRevendaProduto;
    // End of variables declaration//GEN-END:variables
}
