/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mako.view;

import javax.swing.JOptionPane;
import mako.controller.ClienteDAO;
import mako.controller.Relatorio;
import mako.model.Cliente;

/**
 *
 * @author CaioThizio
 */
public class CadastroCliente extends javax.swing.JFrame implements java.io.Serializable{
    private Cliente c = new Cliente();
    /**
     * Creates new form CadastroProduto
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFornecedor = new javax.swing.ButtonGroup();
        buttonGrouptipoPes = new javax.swing.ButtonGroup();
        painelCliente = new javax.swing.JPanel();
        apresentacaoCliente = new javax.swing.JLabel();
        painelCamposCliente = new javax.swing.JPanel();
        labelNomeCliente = new javax.swing.JLabel();
        textNomeCliente = new javax.swing.JTextField();
        labelEndCliente = new javax.swing.JLabel();
        textEndCliente = new javax.swing.JTextField();
        labelIdCliente = new javax.swing.JLabel();
        textIdCliente = new javax.swing.JTextField();
        labelContatoCliente = new javax.swing.JLabel();
        textContatoCliente = new javax.swing.JTextField();
        labelCpfCnpjCliente = new javax.swing.JLabel();
        textCpfCnpj = new javax.swing.JTextField();
        labelObservacoesCliente = new javax.swing.JLabel();
        buttonVoltarCliente = new javax.swing.JButton();
        buttonLimparCliente = new javax.swing.JButton();
        buttonCadastrarCliente = new javax.swing.JButton();
        buttonBanco = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaObsCliente = new javax.swing.JTextArea();
        buttonrRelatorioC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Cliente");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        painelCliente.setBackground(new java.awt.Color(0, 204, 204));
        painelCliente.setForeground(new java.awt.Color(255, 255, 255));
        painelCliente.setPreferredSize(new java.awt.Dimension(720, 600));

        apresentacaoCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        apresentacaoCliente.setForeground(new java.awt.Color(255, 255, 255));
        apresentacaoCliente.setText("Cadastro de Cliente");

        painelCamposCliente.setBackground(new java.awt.Color(255, 255, 255));

        labelNomeCliente.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelNomeCliente.setText("Nome do Cliente:");

        textNomeCliente.setUI(new mako.controller.Watermark("Digite o nome do Cliente...", true));

        labelEndCliente.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelEndCliente.setText("Endereço do Cliente:");

        textEndCliente.setUI(new mako.controller.Watermark("Digite o endereço do Cliente (rua, número, cep, cidade, estado)...", true));

        labelIdCliente.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelIdCliente.setText("ID do Cliente:");

        textIdCliente.setUI(new mako.controller.Watermark("Digite o ID do Cliente...", true));

        labelContatoCliente.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelContatoCliente.setText("Contato do Cliente:");

        textContatoCliente.setUI(new mako.controller.Watermark("Digite um número para contato com o Cliente. ex:(00)0000-0000", true));

        labelCpfCnpjCliente.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelCpfCnpjCliente.setText("CPF/CNPJ:");

        textCpfCnpj.setUI(new mako.controller.Watermark("Digite o CPF ou CNPJ do Cliente...", true));

        labelObservacoesCliente.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelObservacoesCliente.setText("Observações:");

        buttonVoltarCliente.setText("Voltar");
        buttonVoltarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonVoltarClienteMouseClicked(evt);
            }
        });

        buttonLimparCliente.setText("Limpar campos");
        buttonLimparCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLimparClienteMouseClicked(evt);
            }
        });

        buttonCadastrarCliente.setText("Cadastrar");
        buttonCadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCadastrarClienteMouseClicked(evt);
            }
        });
        buttonCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarClienteActionPerformed(evt);
            }
        });

        buttonBanco.setText("Abrir Banco");
        buttonBanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBancoMouseClicked(evt);
            }
        });

        textAreaObsCliente.setColumns(20);
        textAreaObsCliente.setLineWrap(true);
        textAreaObsCliente.setRows(5);
        jScrollPane1.setViewportView(textAreaObsCliente);

        buttonrRelatorioC.setText("Relatório de Clientes");
        buttonrRelatorioC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonrRelatorioCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelCamposClienteLayout = new javax.swing.GroupLayout(painelCamposCliente);
        painelCamposCliente.setLayout(painelCamposClienteLayout);
        painelCamposClienteLayout.setHorizontalGroup(
            painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelObservacoesCliente)
                    .addComponent(labelContatoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelCamposClienteLayout.createSequentialGroup()
                        .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelIdCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelEndCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNomeCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCpfCnpjCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(painelCamposClienteLayout.createSequentialGroup()
                                .addComponent(buttonVoltarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addComponent(buttonLimparCliente)
                                .addGap(97, 97, 97)
                                .addComponent(buttonCadastrarCliente))
                            .addComponent(textNomeCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textEndCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textIdCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCpfCnpj, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textContatoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelCamposClienteLayout.createSequentialGroup()
                                .addComponent(buttonBanco)
                                .addGap(18, 18, 18)
                                .addComponent(buttonrRelatorioC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCamposClienteLayout.setVerticalGroup(
            painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposClienteLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBanco)
                    .addComponent(buttonrRelatorioC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdCliente)
                    .addComponent(textIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeCliente)
                    .addComponent(textNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEndCliente)
                    .addComponent(textEndCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContatoCliente)
                    .addComponent(textContatoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCpfCnpjCliente))
                .addGap(36, 36, 36)
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelObservacoesCliente)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCadastrarCliente)
                    .addComponent(buttonLimparCliente)
                    .addComponent(buttonVoltarCliente))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelClienteLayout = new javax.swing.GroupLayout(painelCliente);
        painelCliente.setLayout(painelClienteLayout);
        painelClienteLayout.setHorizontalGroup(
            painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelClienteLayout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(apresentacaoCliente)
                .addGap(243, 243, 243))
            .addComponent(painelCamposCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelClienteLayout.setVerticalGroup(
            painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelClienteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(apresentacaoCliente)
                .addGap(18, 18, 18)
                .addComponent(painelCamposCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(painelCliente);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLimparClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLimparClienteMouseClicked
        textIdCliente.setText("");
        textNomeCliente.setText("");
        textEndCliente.setText("");
        textContatoCliente.setText("");
        textCpfCnpj.setText("");
        textAreaObsCliente.setText("");
    }//GEN-LAST:event_buttonLimparClienteMouseClicked

    private void buttonCadastrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCadastrarClienteMouseClicked
        int op = JOptionPane.showConfirmDialog(null, "Tem certeza que gostaria de cadastrar o Cliente?", "Cadastro de Cliente", JOptionPane.YES_NO_OPTION);

        if (op == 0){
            c.setId(Integer.parseInt(textIdCliente.getText()));
            c.setNome(textNomeCliente.getText());
            c.setEndereco(textEndCliente.getText());
            c.setContato(textContatoCliente.getText());
            c.setCpfcnpj(textCpfCnpj.getText());
            c.setObs(textAreaObsCliente.getText());
            
            JOptionPane.showMessageDialog(null, ClienteDAO.cadastrar(c), "Cadastro de Cliente", JOptionPane.PLAIN_MESSAGE);
            try{
                ClienteDAO.adicionarClienteBD(c);
                //ClienteDAO.escreveClientes();
                //ClienteDAO.escreveClientesBin();
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Erro!" + e.getMessage(), "Erro no salvamento", JOptionPane.ERROR_MESSAGE);
            }
            
            
        }
    }//GEN-LAST:event_buttonCadastrarClienteMouseClicked

    public void setaTelaUpdate(){
        buttonCadastrarCliente.setText("Atualizar");
        buttonBanco.setVisible(false);
    }
    
    private void buttonCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastrarClienteActionPerformed

    private void buttonVoltarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVoltarClienteMouseClicked
        this.dispose();
    }//GEN-LAST:event_buttonVoltarClienteMouseClicked

    private void buttonBancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBancoMouseClicked
        new BancoClientes().setVisible(true);
    }//GEN-LAST:event_buttonBancoMouseClicked

    private void buttonrRelatorioCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonrRelatorioCMouseClicked
        Relatorio.mostraRelatorioClientes();
    }//GEN-LAST:event_buttonrRelatorioCMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apresentacaoCliente;
    private javax.swing.JButton buttonBanco;
    private javax.swing.JButton buttonCadastrarCliente;
    private javax.swing.ButtonGroup buttonGroupFornecedor;
    private javax.swing.ButtonGroup buttonGrouptipoPes;
    private javax.swing.JButton buttonLimparCliente;
    private javax.swing.JButton buttonVoltarCliente;
    private javax.swing.JButton buttonrRelatorioC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelContatoCliente;
    private javax.swing.JLabel labelCpfCnpjCliente;
    private javax.swing.JLabel labelEndCliente;
    private javax.swing.JLabel labelIdCliente;
    private javax.swing.JLabel labelNomeCliente;
    private javax.swing.JLabel labelObservacoesCliente;
    private javax.swing.JPanel painelCamposCliente;
    private javax.swing.JPanel painelCliente;
    private javax.swing.JTextArea textAreaObsCliente;
    private javax.swing.JTextField textContatoCliente;
    private javax.swing.JTextField textCpfCnpj;
    private javax.swing.JTextField textEndCliente;
    private javax.swing.JTextField textIdCliente;
    private javax.swing.JTextField textNomeCliente;
    // End of variables declaration//GEN-END:variables
}
