/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mako.view;

import java.awt.CardLayout;
import java.awt.Container;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import mako.controller.ClienteDAO;
import mako.controller.FornecedorDAO;
import mako.controller.ProdutoDAO;
import mako.controller.Relatorio;
import mako.model.Cliente;
import mako.model.Fornecedor;
import mako.model.Produto;

/**
 *
 * @author caio.thizio
 */
public class Principal extends javax.swing.JFrame {
    
    public static ArrayList<String> tipos;

    /**
     * Creates new form CardLayout
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMenuInicial = new javax.swing.JPanel();
        botaoCadastroCliente = new javax.swing.JButton();
        botaoCadastroProduto = new javax.swing.JButton();
        botaoCadastroFornecedor = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        labelPrincipal = new javax.swing.JLabel();
        botaoNovaCompra = new javax.swing.JButton();
        painelCliente = new javax.swing.JPanel();
        apresentacaoCliente = new javax.swing.JLabel();
        painelCamposCliente = new javax.swing.JPanel();
        labelNomeCliente = new javax.swing.JLabel();
        textNomeCliente = new javax.swing.JTextField();
        labelEndCliente = new javax.swing.JLabel();
        textEndCliente = new javax.swing.JTextField();
        labelIdCliente = new javax.swing.JLabel();
        textIdCliente = new javax.swing.JTextField();
        labelContatoCliente = new javax.swing.JLabel();
        textContatoCliente = new javax.swing.JTextField();
        labelCpfCnpjCliente = new javax.swing.JLabel();
        textCpfCnpj = new javax.swing.JTextField();
        labelObservacoesCliente = new javax.swing.JLabel();
        buttonVoltarCliente = new javax.swing.JButton();
        buttonLimparCliente = new javax.swing.JButton();
        buttonCadastrarCliente = new javax.swing.JButton();
        buttonBanco = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaObsCliente = new javax.swing.JTextArea();
        buttonrRelatorioC = new javax.swing.JButton();
        painelFornecedor = new javax.swing.JPanel();
        apresentacaoFornecedor = new javax.swing.JLabel();
        painelCamposFornecedor = new javax.swing.JPanel();
        labelNomeFornecedor = new javax.swing.JLabel();
        textNomeFornecedor = new javax.swing.JTextField();
        labelEndFornecedor = new javax.swing.JLabel();
        textEndFornecedor = new javax.swing.JTextField();
        labelIdFornecedor = new javax.swing.JLabel();
        textIdFornecedor = new javax.swing.JTextField();
        labelContatoFornecedor = new javax.swing.JLabel();
        textContatoFornecedor = new javax.swing.JTextField();
        labelPagFornecedor = new javax.swing.JLabel();
        textPagFornecedor = new javax.swing.JTextField();
        labelObservacoesFornecedor = new javax.swing.JLabel();
        buttonVoltarFornecedor = new javax.swing.JButton();
        buttonLimparFornecedor = new javax.swing.JButton();
        buttonCadastrarFornecedor = new javax.swing.JButton();
        buttonSalvarFornecedor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaObsFornecedor = new javax.swing.JTextArea();
        labelTipoFornecedor = new javax.swing.JLabel();
        buttonAliForn = new javax.swing.JRadioButton();
        buttonMlForn = new javax.swing.JRadioButton();
        buttonWishForn = new javax.swing.JRadioButton();
        buttonOutrosForn = new javax.swing.JRadioButton();
        buttonFisForn = new javax.swing.JRadioButton();
        buttonJurForn = new javax.swing.JRadioButton();
        buttonOutrosFornPes = new javax.swing.JRadioButton();
        labelTipoPesFornecedor = new javax.swing.JLabel();
        buttonrRelatorioC1 = new javax.swing.JButton();
        painelProduto = new javax.swing.JPanel();
        apresentacaoProduto = new javax.swing.JLabel();
        painelCamposProduto = new javax.swing.JPanel();
        labelNomeProduto = new javax.swing.JLabel();
        textNomeProduto = new javax.swing.JTextField();
        labelNomeFornProduto = new javax.swing.JLabel();
        textFornProduto = new javax.swing.JTextField();
        labelQtdProduto = new javax.swing.JLabel();
        labelIDProduto = new javax.swing.JLabel();
        textIDProduto = new javax.swing.JTextField();
        labelTipoProduto = new javax.swing.JLabel();
        labelCustoProduto = new javax.swing.JLabel();
        textCustoProduto = new javax.swing.JTextField();
        labelRevendaProduto = new javax.swing.JLabel();
        textRevendaProduto = new javax.swing.JTextField();
        labelObsProduto = new javax.swing.JLabel();
        buttonVoltarProduto = new javax.swing.JButton();
        buttonLimparProduto = new javax.swing.JButton();
        buttonCadastrarProduto = new javax.swing.JButton();
        buttonBanco1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaObsProduto = new javax.swing.JTextArea();
        textQtde = new javax.swing.JTextField();
        buttonrRelatorioC2 = new javax.swing.JButton();
        comboBoxTipo = new javax.swing.JComboBox<>();
        painelVenda = new javax.swing.JPanel();
        apresentacaoVenda = new javax.swing.JLabel();
        painelCamposVenda = new javax.swing.JPanel();
        labelObsVenda = new javax.swing.JLabel();
        buttonVoltarVenda = new javax.swing.JButton();
        buttonLimparVenda = new javax.swing.JButton();
        buttonCadastrarVenda = new javax.swing.JButton();
        buttonBanco2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaObsVenda = new javax.swing.JTextArea();
        labelIDVenda = new javax.swing.JLabel();
        textIDVenda = new javax.swing.JTextField();
        labelClienteVenda = new javax.swing.JLabel();
        comboBoxClienteVenda = new javax.swing.JComboBox<>();
        labelClienteVenda2 = new javax.swing.JLabel();
        comboBoxClienteVenda2 = new javax.swing.JComboBox<>();
        labelClienteVenda3 = new javax.swing.JLabel();
        textIDVenda1 = new javax.swing.JTextField();
        labelClienteVenda4 = new javax.swing.JLabel();
        textIDVenda2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        painelMenuInicial.setBackground(new java.awt.Color(153, 204, 255));
        painelMenuInicial.setMaximumSize(new java.awt.Dimension(720, 600));
        painelMenuInicial.setMinimumSize(new java.awt.Dimension(720, 600));
        painelMenuInicial.setPreferredSize(new java.awt.Dimension(720, 600));

        botaoCadastroCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaoCadastroCliente.setText("Cadastro de Cliente");
        botaoCadastroCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastroClienteMouseClicked(evt);
            }
        });

        botaoCadastroProduto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaoCadastroProduto.setText("Cadastro de Produto");
        botaoCadastroProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastroProdutoMouseClicked(evt);
            }
        });

        botaoCadastroFornecedor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaoCadastroFornecedor.setText("Cadastro de Fornecedor");
        botaoCadastroFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastroFornecedorMouseClicked(evt);
            }
        });
        botaoCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroFornecedorActionPerformed(evt);
            }
        });

        botaoSair.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaoSair.setText("Sair");
        botaoSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSairMouseClicked(evt);
            }
        });

        labelPrincipal.setFont(new java.awt.Font("Constantia", 0, 36)); // NOI18N
        labelPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPrincipal.setText("Mako Store v.1.3.0");

        botaoNovaCompra.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaoNovaCompra.setText("Nova Venda");
        botaoNovaCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoNovaCompraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelMenuInicialLayout = new javax.swing.GroupLayout(painelMenuInicial);
        painelMenuInicial.setLayout(painelMenuInicialLayout);
        painelMenuInicialLayout.setHorizontalGroup(
            painelMenuInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuInicialLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(painelMenuInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoNovaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        painelMenuInicialLayout.setVerticalGroup(
            painelMenuInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMenuInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoNovaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(botaoCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoCadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        getContentPane().add(painelMenuInicial, "cardMenuInicial");

        painelCliente.setBackground(new java.awt.Color(0, 204, 204));
        painelCliente.setForeground(new java.awt.Color(255, 255, 255));
        painelCliente.setPreferredSize(new java.awt.Dimension(720, 600));

        apresentacaoCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        apresentacaoCliente.setForeground(new java.awt.Color(255, 255, 255));
        apresentacaoCliente.setText("Cadastro de Cliente");

        painelCamposCliente.setBackground(new java.awt.Color(255, 255, 255));

        labelNomeCliente.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelNomeCliente.setText("Nome do Cliente:");

        textNomeCliente.setUI(new mako.controller.Watermark("Digite o nome do Cliente...", true));

        labelEndCliente.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelEndCliente.setText("Endereço do Cliente:");

        textEndCliente.setUI(new mako.controller.Watermark("Digite o endereço do Cliente (rua, número, cep, cidade, estado)...", true));

        labelIdCliente.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelIdCliente.setText("ID do Cliente:");

        textIdCliente.setUI(new mako.controller.Watermark("Digite o ID do Cliente...", true));

        labelContatoCliente.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelContatoCliente.setText("Contato do Cliente:");

        textContatoCliente.setUI(new mako.controller.Watermark("Digite um número para contato com o Cliente. ex:(00)0000-0000", true));

        labelCpfCnpjCliente.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelCpfCnpjCliente.setText("CPF/CNPJ:");

        textCpfCnpj.setUI(new mako.controller.Watermark("Digite o CPF ou CNPJ do Cliente...", true));

        labelObservacoesCliente.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelObservacoesCliente.setText("Observações:");

        buttonVoltarCliente.setText("Voltar");
        buttonVoltarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonVoltarClienteMouseClicked(evt);
            }
        });

        buttonLimparCliente.setText("Limpar campos");
        buttonLimparCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLimparClienteMouseClicked(evt);
            }
        });

        buttonCadastrarCliente.setText("Cadastrar");
        buttonCadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCadastrarClienteMouseClicked(evt);
            }
        });
        buttonCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarClienteActionPerformed(evt);
            }
        });

        buttonBanco.setText("Abrir Banco");
        buttonBanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBancoMouseClicked(evt);
            }
        });

        textAreaObsCliente.setColumns(20);
        textAreaObsCliente.setLineWrap(true);
        textAreaObsCliente.setRows(5);
        jScrollPane1.setViewportView(textAreaObsCliente);

        buttonrRelatorioC.setText("Relatório de Clientes");
        buttonrRelatorioC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonrRelatorioCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelCamposClienteLayout = new javax.swing.GroupLayout(painelCamposCliente);
        painelCamposCliente.setLayout(painelCamposClienteLayout);
        painelCamposClienteLayout.setHorizontalGroup(
            painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposClienteLayout.createSequentialGroup()
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCamposClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonVoltarCliente))
                    .addGroup(painelCamposClienteLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelObservacoesCliente)
                            .addComponent(labelContatoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelCamposClienteLayout.createSequentialGroup()
                                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelIdCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelEndCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelNomeCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelCpfCnpjCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(painelCamposClienteLayout.createSequentialGroup()
                                        .addComponent(buttonLimparCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buttonCadastrarCliente))
                                    .addComponent(textNomeCliente)
                                    .addComponent(textEndCliente)
                                    .addComponent(textIdCliente)
                                    .addComponent(textCpfCnpj)
                                    .addComponent(textContatoCliente)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                                    .addGroup(painelCamposClienteLayout.createSequentialGroup()
                                        .addComponent(buttonBanco)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonrRelatorioC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCamposClienteLayout.setVerticalGroup(
            painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposClienteLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBanco)
                    .addComponent(buttonrRelatorioC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdCliente)
                    .addComponent(textIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeCliente)
                    .addComponent(textNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEndCliente)
                    .addComponent(textEndCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContatoCliente)
                    .addComponent(textContatoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCpfCnpjCliente))
                .addGap(36, 36, 36)
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelObservacoesCliente)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(painelCamposClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVoltarCliente)
                    .addComponent(buttonCadastrarCliente)
                    .addComponent(buttonLimparCliente))
                .addContainerGap())
        );

        javax.swing.GroupLayout painelClienteLayout = new javax.swing.GroupLayout(painelCliente);
        painelCliente.setLayout(painelClienteLayout);
        painelClienteLayout.setHorizontalGroup(
            painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCamposCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelClienteLayout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(apresentacaoCliente)
                .addGap(248, 248, 248))
        );
        painelClienteLayout.setVerticalGroup(
            painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelClienteLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(apresentacaoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelCamposCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(painelCliente, "cardCadCliente");

        painelFornecedor.setBackground(new java.awt.Color(0, 204, 204));
        painelFornecedor.setForeground(new java.awt.Color(255, 255, 255));
        painelFornecedor.setPreferredSize(new java.awt.Dimension(720, 600));

        apresentacaoFornecedor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        apresentacaoFornecedor.setForeground(new java.awt.Color(255, 255, 255));
        apresentacaoFornecedor.setText("Cadastro de Fornecedor");

        painelCamposFornecedor.setBackground(new java.awt.Color(255, 255, 255));

        labelNomeFornecedor.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelNomeFornecedor.setText("Nome do Fornecedor:");

        textNomeFornecedor.setUI(new mako.controller.Watermark("Digite o nome do Fornecedor...", true));

        labelEndFornecedor.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelEndFornecedor.setText("Endereço do Fornecedor:");

        textEndFornecedor.setUI(new mako.controller.Watermark("Digite o endereço do Fornecedor...", true));

        labelIdFornecedor.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelIdFornecedor.setText("ID do Fornecedor:");

        textIdFornecedor.setUI(new mako.controller.Watermark("Digite o ID do Fornecedor...", true));

        labelContatoFornecedor.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelContatoFornecedor.setText("Contato do Fornecedor:");

        textContatoFornecedor.setUI(new mako.controller.Watermark("Digite um número para contato com o Fornecedor. ex:(00)0000-0000", true));

        labelPagFornecedor.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelPagFornecedor.setText("Página Fornecedor:");

        textPagFornecedor.setUI(new mako.controller.Watermark("Digite a página web do Fornecedor (caso exista).", true));

        labelObservacoesFornecedor.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelObservacoesFornecedor.setText("Observações:");

        buttonVoltarFornecedor.setText("Voltar");
        buttonVoltarFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonVoltarFornecedorMouseClicked(evt);
            }
        });

        buttonLimparFornecedor.setText("Limpar Campos");
        buttonLimparFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLimparFornecedorMouseClicked(evt);
            }
        });

        buttonCadastrarFornecedor.setText("Cadastrar");
        buttonCadastrarFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCadastrarFornecedorMouseClicked(evt);
            }
        });

        buttonSalvarFornecedor.setText("Abrir Banco");
        buttonSalvarFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSalvarFornecedorMouseClicked(evt);
            }
        });

        textAreaObsFornecedor.setColumns(20);
        textAreaObsFornecedor.setLineWrap(true);
        textAreaObsFornecedor.setRows(5);
        jScrollPane2.setViewportView(textAreaObsFornecedor);

        labelTipoFornecedor.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelTipoFornecedor.setText("Tipo do Fornecedor:");

        buttonAliForn.setBackground(new java.awt.Color(255, 255, 255));
        buttonAliForn.setText("Aliexpress");

        buttonMlForn.setBackground(new java.awt.Color(255, 255, 255));
        buttonMlForn.setText("Mercado Livre");

        buttonWishForn.setBackground(new java.awt.Color(255, 255, 255));
        buttonWishForn.setText("Wish");

        buttonOutrosForn.setBackground(new java.awt.Color(255, 255, 255));
        buttonOutrosForn.setText("Outros");

        buttonFisForn.setBackground(new java.awt.Color(255, 255, 255));
        buttonFisForn.setText("Pessoa Física");

        buttonJurForn.setBackground(new java.awt.Color(255, 255, 255));
        buttonJurForn.setText("Pessoa Juridica");

        buttonOutrosFornPes.setBackground(new java.awt.Color(255, 255, 255));
        buttonOutrosFornPes.setText("Outros");

        labelTipoPesFornecedor.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelTipoPesFornecedor.setText("Tipo da Pessoa:");

        buttonrRelatorioC1.setText("Relatório de Fornecedores");
        buttonrRelatorioC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonrRelatorioC1MouseClicked(evt);
            }
        });
        buttonrRelatorioC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonrRelatorioC1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCamposFornecedorLayout = new javax.swing.GroupLayout(painelCamposFornecedor);
        painelCamposFornecedor.setLayout(painelCamposFornecedorLayout);
        painelCamposFornecedorLayout.setHorizontalGroup(
            painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContatoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelCamposFornecedorLayout.createSequentialGroup()
                        .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelIdFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelEndFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNomeFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTipoPesFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTipoFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPagFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textNomeFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                                .addComponent(textEndFornecedor)
                                .addComponent(textIdFornecedor)
                                .addComponent(textPagFornecedor)
                                .addComponent(textContatoFornecedor))
                            .addGroup(painelCamposFornecedorLayout.createSequentialGroup()
                                .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonAliForn)
                                    .addComponent(buttonFisForn))
                                .addGap(20, 20, 20)
                                .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelCamposFornecedorLayout.createSequentialGroup()
                                        .addComponent(buttonJurForn)
                                        .addGap(16, 16, 16)
                                        .addComponent(buttonOutrosFornPes))
                                    .addGroup(painelCamposFornecedorLayout.createSequentialGroup()
                                        .addComponent(buttonMlForn)
                                        .addGap(20, 20, 20)
                                        .addComponent(buttonWishForn)
                                        .addGap(34, 34, 34)
                                        .addComponent(buttonOutrosForn))))
                            .addGroup(painelCamposFornecedorLayout.createSequentialGroup()
                                .addComponent(buttonSalvarFornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonrRelatorioC1))))
                    .addGroup(painelCamposFornecedorLayout.createSequentialGroup()
                        .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelObservacoesFornecedor)
                            .addComponent(buttonVoltarFornecedor))
                        .addGap(94, 94, 94)
                        .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painelCamposFornecedorLayout.createSequentialGroup()
                                .addComponent(buttonLimparFornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCadastrarFornecedor))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        painelCamposFornecedorLayout.setVerticalGroup(
            painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposFornecedorLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSalvarFornecedor)
                    .addComponent(buttonrRelatorioC1))
                .addGap(18, 18, 18)
                .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdFornecedor)
                    .addComponent(textIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeFornecedor)
                    .addComponent(textNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEndFornecedor)
                    .addComponent(textEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContatoFornecedor)
                    .addComponent(textContatoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPagFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPagFornecedor))
                .addGap(30, 30, 30)
                .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAliForn)
                    .addComponent(buttonMlForn)
                    .addComponent(buttonWishForn)
                    .addComponent(buttonOutrosForn)
                    .addComponent(labelTipoFornecedor))
                .addGap(18, 18, 18)
                .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFisForn)
                    .addComponent(buttonJurForn)
                    .addComponent(buttonOutrosFornPes)
                    .addComponent(labelTipoPesFornecedor))
                .addGap(25, 25, 25)
                .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelObservacoesFornecedor)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCadastrarFornecedor)
                    .addComponent(buttonLimparFornecedor)
                    .addComponent(buttonVoltarFornecedor))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelFornecedorLayout = new javax.swing.GroupLayout(painelFornecedor);
        painelFornecedor.setLayout(painelFornecedorLayout);
        painelFornecedorLayout.setHorizontalGroup(
            painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCamposFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFornecedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(apresentacaoFornecedor)
                .addGap(217, 217, 217))
        );
        painelFornecedorLayout.setVerticalGroup(
            painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFornecedorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(apresentacaoFornecedor)
                .addGap(18, 18, 18)
                .addComponent(painelCamposFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(painelFornecedor, "cardCadFornecedor");

        painelProduto.setBackground(new java.awt.Color(0, 204, 204));
        painelProduto.setForeground(new java.awt.Color(255, 255, 255));
        painelProduto.setPreferredSize(new java.awt.Dimension(720, 600));

        apresentacaoProduto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        apresentacaoProduto.setForeground(new java.awt.Color(255, 255, 255));
        apresentacaoProduto.setText("Cadastro de Produtos");

        painelCamposProduto.setBackground(new java.awt.Color(255, 255, 255));

        labelNomeProduto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelNomeProduto.setText("Nome do Produto:");

        textNomeProduto.setUI(new mako.controller.Watermark("Digite o nome do Produto...", true));

        labelNomeFornProduto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelNomeFornProduto.setText("Nome do Fornecedor:");

        textFornProduto.setUI(new mako.controller.Watermark("Digite o nome do Fornecedor deste Produto...", true));

        labelQtdProduto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelQtdProduto.setText("Quantidade:");

        labelIDProduto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelIDProduto.setText("ID do Produto:");

        textIDProduto.setUI(new mako.controller.Watermark("Digite o ID do Produto...", true));

        labelTipoProduto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelTipoProduto.setText("Tipo do Produto:");

        labelCustoProduto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelCustoProduto.setText("Preço de Custo (R$):");

        textCustoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCustoProdutoActionPerformed(evt);
            }
        });

        labelRevendaProduto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelRevendaProduto.setText("Preço de Revenda (R$):");

        textRevendaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRevendaProdutoActionPerformed(evt);
            }
        });

        labelObsProduto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelObsProduto.setText("Observações:");

        buttonVoltarProduto.setText("Voltar");
        buttonVoltarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonVoltarProdutoMouseClicked(evt);
            }
        });

        buttonLimparProduto.setText("Limpar Campos");
        buttonLimparProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLimparProdutoMouseClicked(evt);
            }
        });

        buttonCadastrarProduto.setText("Cadastrar");
        buttonCadastrarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCadastrarProdutoMouseClicked(evt);
            }
        });

        buttonBanco1.setText("Abrir Banco");
        buttonBanco1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBanco1MouseClicked(evt);
            }
        });

        textAreaObsProduto.setColumns(20);
        textAreaObsProduto.setLineWrap(true);
        textAreaObsProduto.setRows(5);
        jScrollPane3.setViewportView(textAreaObsProduto);

        textQtde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQtdeActionPerformed(evt);
            }
        });

        buttonrRelatorioC2.setText("Relatório de Produtos");
        buttonrRelatorioC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonrRelatorioC2MouseClicked(evt);
            }
        });
        buttonrRelatorioC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonrRelatorioC2ActionPerformed(evt);
            }
        });

        popularComboBox();

        javax.swing.GroupLayout painelCamposProdutoLayout = new javax.swing.GroupLayout(painelCamposProduto);
        painelCamposProduto.setLayout(painelCamposProdutoLayout);
        painelCamposProdutoLayout.setHorizontalGroup(
            painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                        .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCamposProdutoLayout.createSequentialGroup()
                                .addComponent(labelCustoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                                .addComponent(labelRevendaProduto)
                                .addGap(9, 9, 9)))
                        .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(textCustoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textRevendaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                        .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelIDProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNomeFornProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(labelNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                                .addComponent(buttonBanco1)
                                .addGap(18, 18, 18)
                                .addComponent(buttonrRelatorioC2))
                            .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                                .addComponent(textFornProduto)
                                .addComponent(textIDProduto))))
                    .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                        .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTipoProduto)
                            .addComponent(labelQtdProduto)
                            .addComponent(labelObsProduto)
                            .addComponent(buttonVoltarProduto))
                        .addGap(56, 56, 56)
                        .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCamposProdutoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonLimparProduto)
                                .addGap(99, 99, 99)
                                .addComponent(buttonCadastrarProduto))
                            .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                                    .addComponent(textQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        painelCamposProdutoLayout.setVerticalGroup(
            painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBanco1)
                    .addComponent(buttonrRelatorioC2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIDProduto)
                    .addComponent(textIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeProduto)
                    .addComponent(textNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeFornProduto)
                    .addComponent(textFornProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCustoProduto)
                    .addComponent(textCustoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRevendaProduto)
                    .addComponent(textRevendaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQtdProduto)
                    .addComponent(textQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoProduto)
                    .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelCamposProdutoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labelObsProduto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(painelCamposProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVoltarProduto)
                    .addComponent(buttonLimparProduto)
                    .addComponent(buttonCadastrarProduto))
                .addContainerGap())
        );

        javax.swing.GroupLayout painelProdutoLayout = new javax.swing.GroupLayout(painelProduto);
        painelProduto.setLayout(painelProdutoLayout);
        painelProdutoLayout.setHorizontalGroup(
            painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelProdutoLayout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(apresentacaoProduto)
                .addGap(233, 233, 233))
            .addComponent(painelCamposProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelProdutoLayout.setVerticalGroup(
            painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProdutoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(apresentacaoProduto)
                .addGap(18, 18, 18)
                .addComponent(painelCamposProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(painelProduto, "cardCadProduto");

        painelVenda.setBackground(new java.awt.Color(0, 204, 204));
        painelVenda.setForeground(new java.awt.Color(255, 255, 255));
        painelVenda.setPreferredSize(new java.awt.Dimension(720, 600));

        apresentacaoVenda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        apresentacaoVenda.setForeground(new java.awt.Color(255, 255, 255));
        apresentacaoVenda.setText("Nova Venda");

        painelCamposVenda.setBackground(new java.awt.Color(255, 255, 255));

        labelObsVenda.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelObsVenda.setText("Observações:");

        buttonVoltarVenda.setText("Voltar");
        buttonVoltarVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonVoltarVendaMouseClicked(evt);
            }
        });

        buttonLimparVenda.setText("Limpar Campos");
        buttonLimparVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLimparVendaMouseClicked(evt);
            }
        });

        buttonCadastrarVenda.setText("Cadastrar");
        buttonCadastrarVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCadastrarVendaMouseClicked(evt);
            }
        });

        buttonBanco2.setText("Abrir Banco");
        buttonBanco2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBanco2MouseClicked(evt);
            }
        });

        textAreaObsVenda.setColumns(20);
        textAreaObsVenda.setLineWrap(true);
        textAreaObsVenda.setRows(5);
        jScrollPane4.setViewportView(textAreaObsVenda);

        labelIDVenda.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelIDVenda.setText("ID da Venda:");

        textIDProduto.setUI(new mako.controller.Watermark("Digite o ID da Venda...", true));
        textIDVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDVendaActionPerformed(evt);
            }
        });

        labelClienteVenda.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelClienteVenda.setText("Cliente:");

        labelClienteVenda2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelClienteVenda2.setText("Produto:");

        labelClienteVenda3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelClienteVenda3.setText("Quantidade:");

        textIDProduto.setUI(new mako.controller.Watermark("Digite o ID da Venda...", true));
        textIDVenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDVenda1ActionPerformed(evt);
            }
        });

        labelClienteVenda4.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelClienteVenda4.setText("Preço:");

        textIDProduto.setUI(new mako.controller.Watermark("Digite o ID da Venda...", true));
        textIDVenda2.setEnabled(false);
        textIDVenda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDVenda2ActionPerformed(evt);
            }
        });

        jButton1.setText("Calcular Preço");

        javax.swing.GroupLayout painelCamposVendaLayout = new javax.swing.GroupLayout(painelCamposVenda);
        painelCamposVenda.setLayout(painelCamposVendaLayout);
        painelCamposVendaLayout.setHorizontalGroup(
            painelCamposVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCamposVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelClienteVenda4)
                    .addComponent(labelClienteVenda3)
                    .addComponent(labelClienteVenda)
                    .addComponent(labelIDVenda)
                    .addGroup(painelCamposVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelObsVenda)
                        .addComponent(buttonVoltarVenda))
                    .addComponent(labelClienteVenda2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCamposVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCamposVendaLayout.createSequentialGroup()
                        .addComponent(buttonBanco2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCamposVendaLayout.createSequentialGroup()
                        .addGroup(painelCamposVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboBoxClienteVenda, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textIDVenda, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCamposVendaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonLimparVenda)
                                .addGap(99, 99, 99)
                                .addComponent(buttonCadastrarVenda))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelCamposVendaLayout.createSequentialGroup()
                                .addComponent(textIDVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addGap(0, 355, Short.MAX_VALUE))
                            .addComponent(comboBoxClienteVenda2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(60, 60, 60))
                    .addGroup(painelCamposVendaLayout.createSequentialGroup()
                        .addComponent(textIDVenda2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        painelCamposVendaLayout.setVerticalGroup(
            painelCamposVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonBanco2)
                .addGap(30, 30, 30)
                .addGroup(painelCamposVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIDVenda)
                    .addComponent(textIDVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClienteVenda)
                    .addComponent(comboBoxClienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClienteVenda2)
                    .addComponent(comboBoxClienteVenda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(painelCamposVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClienteVenda3)
                    .addComponent(textIDVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(painelCamposVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClienteVenda4)
                    .addComponent(textIDVenda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(painelCamposVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelCamposVendaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labelObsVenda)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(painelCamposVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVoltarVenda)
                    .addComponent(buttonLimparVenda)
                    .addComponent(buttonCadastrarVenda))
                .addContainerGap())
        );

        javax.swing.GroupLayout painelVendaLayout = new javax.swing.GroupLayout(painelVenda);
        painelVenda.setLayout(painelVendaLayout);
        painelVendaLayout.setHorizontalGroup(
            painelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCamposVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelVendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(apresentacaoVenda)
                .addGap(294, 294, 294))
        );
        painelVendaLayout.setVerticalGroup(
            painelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVendaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(apresentacaoVenda)
                .addGap(18, 18, 18)
                .addComponent(painelCamposVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(painelVenda, "cardCadVenda");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastroClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastroClienteMouseClicked
        Container cards = getContentPane();

        CardLayout cl = (CardLayout) cards.getLayout();
        cl.show(cards, "cardCadCliente");
    }//GEN-LAST:event_botaoCadastroClienteMouseClicked

    private void botaoCadastroProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastroProdutoMouseClicked
        Container cards = getContentPane();

        CardLayout cl = (CardLayout) cards.getLayout();
        cl.show(cards, "cardCadProduto");
    }//GEN-LAST:event_botaoCadastroProdutoMouseClicked

    private void botaoCadastroFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastroFornecedorMouseClicked
        Container cards = getContentPane();

        CardLayout cl = (CardLayout) cards.getLayout();
        cl.show(cards, "cardCadFornecedor");
    }//GEN-LAST:event_botaoCadastroFornecedorMouseClicked

    private void botaoSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_botaoSairMouseClicked

    private void buttonVoltarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVoltarClienteMouseClicked
        Container cards = getContentPane();

        CardLayout cl = (CardLayout) cards.getLayout();
        cl.show(cards, "cardMenuInicial");
    }//GEN-LAST:event_buttonVoltarClienteMouseClicked

    private void buttonLimparClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLimparClienteMouseClicked
        textIdCliente.setText("");
        textNomeCliente.setText("");
        textEndCliente.setText("");
        textContatoCliente.setText("");
        textCpfCnpj.setText("");
        textAreaObsCliente.setText("");
    }//GEN-LAST:event_buttonLimparClienteMouseClicked

    private void buttonCadastrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCadastrarClienteMouseClicked
        int op = JOptionPane.showConfirmDialog(null, "Tem certeza que gostaria de cadastrar o Cliente?", "Cadastro de Cliente", JOptionPane.YES_NO_OPTION);
        Cliente c = new Cliente();
        if (op == 0) {
            c.setId(Integer.parseInt(textIdCliente.getText()));
            c.setNome(textNomeCliente.getText());
            c.setEndereco(textEndCliente.getText());
            c.setContato(textContatoCliente.getText());
            c.setCpfcnpj(textCpfCnpj.getText());
            c.setObs(textAreaObsCliente.getText());
            
            if(ClienteDAO.newCliente(c))
                JOptionPane.showMessageDialog(null, "Cliente "+c.getNome()+" cadastrado com sucesso!", "Cadastro de Cliente", JOptionPane.PLAIN_MESSAGE);
           
        }
    }//GEN-LAST:event_buttonCadastrarClienteMouseClicked

    private void buttonCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastrarClienteActionPerformed

    private void buttonBancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBancoMouseClicked
        new BancoClientes().setVisible(true);
    }//GEN-LAST:event_buttonBancoMouseClicked

    private void buttonrRelatorioCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonrRelatorioCMouseClicked
        Relatorio.mostraRelatorioClientes();
    }//GEN-LAST:event_buttonrRelatorioCMouseClicked

    private void buttonVoltarFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVoltarFornecedorMouseClicked
        Container cards = getContentPane();

        CardLayout cl = (CardLayout) cards.getLayout();
        cl.show(cards, "cardMenuInicial");
    }//GEN-LAST:event_buttonVoltarFornecedorMouseClicked

    private void buttonLimparFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLimparFornecedorMouseClicked
        textIdFornecedor.setText("");
        textNomeFornecedor.setText("");
        textEndFornecedor.setText("");
        textContatoFornecedor.setText("");
        textPagFornecedor.setText("");
        textAreaObsFornecedor.setText("");
    }//GEN-LAST:event_buttonLimparFornecedorMouseClicked

    private void buttonCadastrarFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCadastrarFornecedorMouseClicked
        int op = JOptionPane.showConfirmDialog(null, "Tem certeza que gostaria de cadastrar o fornecedor?", "Cadastro de Fornecedor", JOptionPane.YES_NO_OPTION);

        Fornecedor f = new Fornecedor();

        if (op == 0) {

            f.setId(Integer.parseInt(textIdFornecedor.getText()));
            f.setNome(textNomeFornecedor.getText());
            f.setEndereco(textEndFornecedor.getText());
            f.setContato(textContatoFornecedor.getText());
            f.setPagina(textPagFornecedor.getText());
            f.setObs(textAreaObsFornecedor.getText());

            if (buttonAliForn.isSelected()) {
                f.setTipo("AliExpress");
            }
            if (buttonMlForn.isSelected()) {
                f.setTipo("Mercado Livre");
            }
            if (buttonWishForn.isSelected()) {
                f.setTipo("Wish");
            }
            if (buttonOutrosForn.isSelected()) {
                f.setTipo("Outros");
            }

            if (buttonFisForn.isSelected()) {
                f.setTipoPes("Pessoa Física");
            }
            if (buttonJurForn.isSelected()) {
                f.setTipoPes("Pessoa Jurídica");
            }
            if (buttonOutrosFornPes.isSelected()) {
                f.setTipoPes("Outros");
            }
            
            if(FornecedorDAO.newFornecedor(f))
                JOptionPane.showMessageDialog(null, "Fornecedor "+f.getNome()+" cadastrado com sucesso!", "Cadastro de Fornecedor", JOptionPane.PLAIN_MESSAGE);
            
        }
    }//GEN-LAST:event_buttonCadastrarFornecedorMouseClicked

    private void buttonSalvarFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSalvarFornecedorMouseClicked
        new BancoFornecedores().setVisible(true);
    }//GEN-LAST:event_buttonSalvarFornecedorMouseClicked

    private void buttonrRelatorioC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonrRelatorioC1MouseClicked
        Relatorio.mostraRelatorioFornecedores();
    }//GEN-LAST:event_buttonrRelatorioC1MouseClicked

    private void buttonrRelatorioC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonrRelatorioC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonrRelatorioC1ActionPerformed

    private void botaoCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastroFornecedorActionPerformed

    private void textCustoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCustoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCustoProdutoActionPerformed

    private void textRevendaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRevendaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRevendaProdutoActionPerformed

    private void buttonVoltarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVoltarProdutoMouseClicked
        Container cards = getContentPane();

        CardLayout cl = (CardLayout) cards.getLayout();
        cl.show(cards, "cardMenuInicial");
    }//GEN-LAST:event_buttonVoltarProdutoMouseClicked

    private void buttonLimparProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLimparProdutoMouseClicked
        textIDProduto.setText("");
        textNomeProduto.setText("");
        textFornProduto.setText("");
        textCustoProduto.setText("");
        textRevendaProduto.setText("");
        textAreaObsProduto.setText("");
        textQtde.setText("");
        //textTipo.setText("");
    }//GEN-LAST:event_buttonLimparProdutoMouseClicked

    private void buttonCadastrarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCadastrarProdutoMouseClicked
        int op = JOptionPane.showConfirmDialog(null, "Tem certeza que gostaria de cadastrar o produto?", "Cadastro de Produto", JOptionPane.YES_NO_OPTION);
        Produto p = new Produto();
        if (op == 0){

            p.setId(Integer.parseInt(textIDProduto.getText()));
            p.setNome(textNomeProduto.getText());
            p.setPrecoCusto(Double.parseDouble(textCustoProduto.getText()));
            p.setPrecoRevenda(Double.parseDouble(textRevendaProduto.getText()));
            p.setQtde(Integer.parseInt(textQtde.getText()));
            p.setListaTipo(comboBoxTipo.getSelectedItem().toString());
            p.setObs(textAreaObsProduto.getText());

            if(ProdutoDAO.newProduto(p))
                JOptionPane.showMessageDialog(null,"Produto "+p.getNome()+" cadastrado com sucesso!", "Cadastro de Produto", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_buttonCadastrarProdutoMouseClicked

    private void buttonBanco1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBanco1MouseClicked
        new BancoProdutos().setVisible(true);
    }//GEN-LAST:event_buttonBanco1MouseClicked

    private void textQtdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQtdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQtdeActionPerformed

    private void buttonrRelatorioC2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonrRelatorioC2MouseClicked
        Relatorio.mostraRelatorioProdutos();
    }//GEN-LAST:event_buttonrRelatorioC2MouseClicked

    private void buttonrRelatorioC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonrRelatorioC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonrRelatorioC2ActionPerformed

    private void botaoNovaCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoNovaCompraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoNovaCompraMouseClicked

    private void buttonVoltarVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVoltarVendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVoltarVendaMouseClicked

    private void buttonLimparVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLimparVendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLimparVendaMouseClicked

    private void buttonCadastrarVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCadastrarVendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastrarVendaMouseClicked

    private void buttonBanco2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBanco2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBanco2MouseClicked

    private void textIDVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDVendaActionPerformed

    private void textIDVenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDVenda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDVenda1ActionPerformed

    private void textIDVenda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDVenda2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDVenda2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }
    
    public void popularComboBox(){
        tipos = new ArrayList<>();
        
        tipos.add("Pincel/Kit");
        tipos.add("Paleta");
        tipos.add("Batom");
        tipos.add("Sombra");
        tipos.add("Blush");
        tipos.add("Iluminador");
        tipos.add("Rímel");
        tipos.add("Lápis de Olho");
        tipos.add("Delineador");
        tipos.add("Outros");
        
        tipos.forEach((tipo) -> {
            comboBoxTipo.addItem(tipo);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apresentacaoCliente;
    private javax.swing.JLabel apresentacaoFornecedor;
    private javax.swing.JLabel apresentacaoProduto;
    private javax.swing.JLabel apresentacaoVenda;
    private javax.swing.JButton botaoCadastroCliente;
    private javax.swing.JButton botaoCadastroFornecedor;
    private javax.swing.JButton botaoCadastroProduto;
    private javax.swing.JButton botaoNovaCompra;
    private javax.swing.JButton botaoSair;
    private javax.swing.JRadioButton buttonAliForn;
    private javax.swing.JButton buttonBanco;
    private javax.swing.JButton buttonBanco1;
    private javax.swing.JButton buttonBanco2;
    private javax.swing.JButton buttonCadastrarCliente;
    private javax.swing.JButton buttonCadastrarFornecedor;
    private javax.swing.JButton buttonCadastrarProduto;
    private javax.swing.JButton buttonCadastrarVenda;
    private javax.swing.JRadioButton buttonFisForn;
    private javax.swing.JRadioButton buttonJurForn;
    private javax.swing.JButton buttonLimparCliente;
    private javax.swing.JButton buttonLimparFornecedor;
    private javax.swing.JButton buttonLimparProduto;
    private javax.swing.JButton buttonLimparVenda;
    private javax.swing.JRadioButton buttonMlForn;
    private javax.swing.JRadioButton buttonOutrosForn;
    private javax.swing.JRadioButton buttonOutrosFornPes;
    private javax.swing.JButton buttonSalvarFornecedor;
    private javax.swing.JButton buttonVoltarCliente;
    private javax.swing.JButton buttonVoltarFornecedor;
    private javax.swing.JButton buttonVoltarProduto;
    private javax.swing.JButton buttonVoltarVenda;
    private javax.swing.JRadioButton buttonWishForn;
    private javax.swing.JButton buttonrRelatorioC;
    private javax.swing.JButton buttonrRelatorioC1;
    private javax.swing.JButton buttonrRelatorioC2;
    private javax.swing.JComboBox<String> comboBoxClienteVenda;
    private javax.swing.JComboBox<String> comboBoxClienteVenda2;
    private javax.swing.JComboBox<String> comboBoxTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelClienteVenda;
    private javax.swing.JLabel labelClienteVenda2;
    private javax.swing.JLabel labelClienteVenda3;
    private javax.swing.JLabel labelClienteVenda4;
    private javax.swing.JLabel labelContatoCliente;
    private javax.swing.JLabel labelContatoFornecedor;
    private javax.swing.JLabel labelCpfCnpjCliente;
    private javax.swing.JLabel labelCustoProduto;
    private javax.swing.JLabel labelEndCliente;
    private javax.swing.JLabel labelEndFornecedor;
    private javax.swing.JLabel labelIDProduto;
    private javax.swing.JLabel labelIDVenda;
    private javax.swing.JLabel labelIdCliente;
    private javax.swing.JLabel labelIdFornecedor;
    private javax.swing.JLabel labelNomeCliente;
    private javax.swing.JLabel labelNomeFornProduto;
    private javax.swing.JLabel labelNomeFornecedor;
    private javax.swing.JLabel labelNomeProduto;
    private javax.swing.JLabel labelObsProduto;
    private javax.swing.JLabel labelObsVenda;
    private javax.swing.JLabel labelObservacoesCliente;
    private javax.swing.JLabel labelObservacoesFornecedor;
    private javax.swing.JLabel labelPagFornecedor;
    private javax.swing.JLabel labelPrincipal;
    private javax.swing.JLabel labelQtdProduto;
    private javax.swing.JLabel labelRevendaProduto;
    private javax.swing.JLabel labelTipoFornecedor;
    private javax.swing.JLabel labelTipoPesFornecedor;
    private javax.swing.JLabel labelTipoProduto;
    private javax.swing.JPanel painelCamposCliente;
    private javax.swing.JPanel painelCamposFornecedor;
    private javax.swing.JPanel painelCamposProduto;
    private javax.swing.JPanel painelCamposVenda;
    private javax.swing.JPanel painelCliente;
    private javax.swing.JPanel painelFornecedor;
    private javax.swing.JPanel painelMenuInicial;
    private javax.swing.JPanel painelProduto;
    private javax.swing.JPanel painelVenda;
    private javax.swing.JTextArea textAreaObsCliente;
    private javax.swing.JTextArea textAreaObsFornecedor;
    private javax.swing.JTextArea textAreaObsProduto;
    private javax.swing.JTextArea textAreaObsVenda;
    private javax.swing.JTextField textContatoCliente;
    private javax.swing.JTextField textContatoFornecedor;
    private javax.swing.JTextField textCpfCnpj;
    private javax.swing.JTextField textCustoProduto;
    private javax.swing.JTextField textEndCliente;
    private javax.swing.JTextField textEndFornecedor;
    private javax.swing.JTextField textFornProduto;
    private javax.swing.JTextField textIDProduto;
    private javax.swing.JTextField textIDVenda;
    private javax.swing.JTextField textIDVenda1;
    private javax.swing.JTextField textIDVenda2;
    private javax.swing.JTextField textIdCliente;
    private javax.swing.JTextField textIdFornecedor;
    private javax.swing.JTextField textNomeCliente;
    private javax.swing.JTextField textNomeFornecedor;
    private javax.swing.JTextField textNomeProduto;
    private javax.swing.JTextField textPagFornecedor;
    private javax.swing.JTextField textQtde;
    private javax.swing.JTextField textRevendaProduto;
    // End of variables declaration//GEN-END:variables
}
